name: Arc
main: arc.Arc
version: "1.0"
api: ["1.0.0"]

permissions:
  arc.notify:
    description: Allows the player to view violations.
    default: true
  arc.exempt:
    description: Exempts players from checks.
    default: false